### PR TITLE
bump thriftpy version to 0.3.3.1

### PR DESCRIPTION
**Pull request by wkingfly**

### CODE REVIEW

**Comment by wkingfly** [comment]
@wooparadog

**Comment by wkingfly** [comment]
And a new version please

**Comment by wooparadog** [comment]
0.3.3.1 hasn't been officially published, it's better we lock thriftpy version in our own projects.

**Comment by wkingfly** [comment]
OK.

Haochuan Guo <notifications@github.com>于2016年1月28日周四 下午9:56写道：

**Pull request closed without merging**
